In [1]:
import numpy as np

In [2]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [3]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [4]:
data= np.random.randn(7,4)

In [5]:
data

array([[ 0.54506419,  0.43195055, -0.1567689 , -0.86152896],
       [ 1.09535005, -0.13796397, -1.70004596, -0.58133649],
       [ 1.76008414,  0.3564604 , -1.21739181, -0.15797797],
       [-1.35478822, -2.0149981 ,  1.01423925,  1.89603178],
       [ 0.63877064,  1.24374401,  0.08336807, -0.99965909],
       [ 0.74135492,  0.1570974 ,  0.32558259, -1.99149405],
       [-0.20658352,  0.52433712, -0.51420346, -0.64775786]])

In [6]:
data = np.random.randn(7,4)

In [11]:
data

array([[-0.3819944 , -1.0752691 , -0.1610234 ,  1.53222187],
       [-1.28038358,  1.63453028,  1.82100441, -1.13121647],
       [ 0.61053743,  0.19989739, -0.51691118, -0.48917101],
       [-1.29968494, -1.34888925, -0.37340861,  0.96085907],
       [-1.71830686,  0.68173303,  1.29063087,  0.3034356 ],
       [ 0.50786118,  0.55125197,  1.58647099, -0.53314179],
       [ 0.41765586, -0.04385512,  1.3829929 , -0.66263421]])

In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Bob', 'Joe', 'Will'])

In [12]:
names == 'Bob'

array([ True, False, False,  True,  True, False, False], dtype=bool)

In [9]:
data[names == 'Bob']

array([[-0.3819944 , -1.0752691 , -0.1610234 ,  1.53222187],
       [-1.29968494, -1.34888925, -0.37340861,  0.96085907],
       [-1.71830686,  0.68173303,  1.29063087,  0.3034356 ]])

In [10]:
data[names == 'Bob', 2]

array([-0.1610234 , -0.37340861,  1.29063087])

In [13]:
data[names == 'Bob', :2]

array([[-0.3819944 , -1.0752691 ],
       [-1.29968494, -1.34888925],
       [-1.71830686,  0.68173303]])

In [15]:
mask = (names == 'BOb')| (names == 'Will')

In [16]:
data[mask]

array([[ 0.61053743,  0.19989739, -0.51691118, -0.48917101],
       [ 0.41765586, -0.04385512,  1.3829929 , -0.66263421]])

In [17]:
a = np.array ([[1, 2], [3, 4]])

In [18]:
a.dtype.itemsize

4

In [19]:
a.dtype.byteorder

'='

In [2]:
import numpy as np

In [3]:
t = np.dtype('float64')

In [4]:
t.type

numpy.float64

In [5]:
t.char

'd'

In [6]:
t.str

'<f8'

In [7]:
a = np.array ([[1, 2], [3, 4]])

In [13]:
a.astype(np.str_, 12)

array([['1', '2'],
       ['3', '4']], 
      dtype='|S11')

In [2]:
import numpy as np

In [3]:
t = np.dtype([('name', np.str_,40), ('numitems', np.int32), ('price', np.float32)])

In [4]:
print t

[('name', 'S40'), ('numitems', '<i4'), ('price', '<f4')]


In [13]:
itemz = np.array([('meaning of life', 12, 3.2)],dtype = t)

In [14]:
print itemz[0]

('meaning of life', 12, 3.200000047683716)


In [15]:
a = np.arange(9)

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
print a[3:7]

[3 4 5 6]


In [18]:
print a[3:7:2]

[3 5]


In [19]:
print a[::-1]

[8 7 6 5 4 3 2 1 0]


In [20]:
s = slice(3,7,2)

In [21]:
print a[s]

[3 5]


In [23]:
b = np.arange(24).reshape(2, 3, 4)

In [24]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
print b[0, 0, 0]

0


In [26]:
print b[:, 0, 0]

[ 0 12]


In [27]:
print b[0, :, :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
print b[0, ...]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
print b[:, :, ::2]

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [30]:
print b[... , 1]

[[ 1  5  9]
 [13 17 21]]


In [31]:
print b[:, 1]

[[ 4  5  6  7]
 [16 17 18 19]]


In [32]:
b = np.arange(24).reshape(2, 3, 4)

In [35]:
print b.ravel()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [36]:
print b.flatten()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
b.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [40]:
b.shape = (3, 8)

In [41]:
print b

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [42]:
print b.transpose()

[[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]


In [43]:
b.resize((2,12))

In [44]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [45]:
a = np.arange(9).reshape(3, 3)

In [46]:
print a 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
b = a * 2

In [48]:
print b

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [50]:
print np.hstack((a, b))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [51]:
print np.concatenate((a, b), axis = 1)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [52]:
print np.vstack((a, b))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [53]:
print np.concatenate((a, b), axis = 0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [54]:
print np.dstack((a, b))

[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [55]:
oned = np.arange(2)

In [56]:
print oned

[0 1]


In [57]:
twice_oned = oned * 2

In [59]:
print np.column_stack((oned, twice_oned))

[[0 0]
 [1 2]]


In [60]:
print np.column_stack((a, b))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [61]:
print np.row_stack((a, b))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [62]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
print np.hsplit(a, 3)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [70]:
print np.split(a, 3, axis=1)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [75]:
print np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [76]:
print np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [77]:
c = np.arange(27).reshape(3, 3, 3)

In [80]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
print np.dsplit(c, 3)

[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


In [81]:
b = np.arange(24).reshape(2,12)

In [82]:
b.ndim

2

In [83]:
b.size

24

In [85]:
b.itemsize

4

In [86]:
b.nbytes

96

In [87]:
print b.flat[3]

3


In [88]:
print b.flat[[1,4]]

[1 4]


In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [3]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [4]:
cond = np.array([True, False, True, True, False])

In [7]:
result = np.where(cond, xarr, yarr)

In [8]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [22]:
arr = np.random.randn(4, 4)

In [23]:
arr

array([[ 1.12520899, -1.46363208,  0.07667586,  0.36650681],
       [ 0.11183554,  0.86515512,  0.00942321,  1.45737081],
       [ 0.51478028, -2.02864057, -0.97969257,  1.43433909],
       [-0.47323746,  0.18205485,  0.01718859,  1.38278638]])

In [24]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2, -2, -2,  2],
       [-2,  2,  2,  2]])

In [25]:
import sys

In [27]:
c, v = np.loadtxt('data.csv', delimiter=',', usecols=(6, 7), unpack = True)