In [2]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.arrat(data1)

AttributeError: 'module' object has no attribute 'arrat'

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
arr1.ndim

1

In [7]:
arr1.shape

(5L,)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
np.zeros(2,3)

TypeError: data type not understood

In [10]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.empty((2,3,2))

array([[[  4.44659081e-323,   6.36598737e-314],
        [  0.00000000e+000,   1.27319747e-313],
        [  1.27319747e-313,   1.27319747e-313]],

       [[  1.27319747e-313,   1.27319747e-313],
        [  0.00000000e+000,   4.44659081e-323],
        [  2.54639495e-313,   6.42285340e-323]]])

In [13]:
np.arrange(10)

AttributeError: 'module' object has no attribute 'arrange'

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros_like(arr1)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.ones_like(arr1)

array([ 1.,  1.,  1.,  1.,  1.])

In [17]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [18]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [20]:
arr2

array([1, 2, 3])

In [21]:
arr2.astype(np.float64)

array([ 1.,  2.,  3.])

In [22]:
arr2

array([1, 2, 3])

In [23]:
arr2.astype(np.str)

array(['1', '2', '3'], 
      dtype='|S11')

In [24]:
arr1[0]

6.0

In [25]:
arr2[0:2]

array([1, 2])

In [26]:
np.array((2,3))

array([2, 3])

In [27]:
np.ones((2))

array([ 1.,  1.])

In [28]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:

np.ones((2,3,4))
Out[29]:
array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [31]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
old_values = arr3d[0].copy()

In [33]:
arr3d[0] = 42

In [34]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[0] = old_values

In [36]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
data = randn(7, 4)

NameError: name 'randn' is not defined

In [38]:
data = np.randn(7,4)

AttributeError: 'module' object has no attribute 'randn'

In [39]:
import random as randn

In [40]:
data = np.randn(7,4)

AttributeError: 'module' object has no attribute 'randn'

In [41]:
import np.random as randn

ImportError: No module named np.random

In [42]:
import random from np

SyntaxError: invalid syntax (<ipython-input-42-82f4e50f8c29>, line 1)

In [43]:
data = np.random.randn(7,4)

In [44]:
data

array([[ 0.48938567, -0.81013985,  0.62718163, -0.19480145],
       [-0.61400141,  1.41869791, -0.30484098, -0.93576705],
       [ 0.03530884,  0.75096418,  0.24229087, -0.56323824],
       [-1.17579373,  0.17093518,  0.19838969,  0.25842798],
       [-0.89829691,  1.79172064, -0.1180776 , -1.03438802],
       [ 0.97080162, -0.57825416,  0.3414156 ,  0.10957875],
       [-1.25367638,  0.1462345 , -0.41534787, -2.07002304]])

In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Bob', 'Joe', 'Will'])

In [46]:
names = 'Bob'

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Bob', 'Joe', 'Will'])

In [48]:
names == 'Bob'

array([ True, False, False,  True,  True, False, False], dtype=bool)

In [49]:
data[names == 'Bob']

array([[ 0.48938567, -0.81013985,  0.62718163, -0.19480145],
       [-1.17579373,  0.17093518,  0.19838969,  0.25842798],
       [-0.89829691,  1.79172064, -0.1180776 , -1.03438802]])

In [50]:
data[names == 'Bob', :2]

array([[ 0.48938567, -0.81013985],
       [-1.17579373,  0.17093518],
       [-0.89829691,  1.79172064]])

In [51]:
data[-(names == 'Bob'), 1:]

C:\Users\Administrator\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 1.41869791, -0.30484098, -0.93576705],
       [ 0.75096418,  0.24229087, -0.56323824],
       [-0.57825416,  0.3414156 ,  0.10957875],
       [ 0.1462345 , -0.41534787, -2.07002304]])

In [52]:
mask = names == 'Bob' | names == ‘Will’

SyntaxError: invalid syntax (<ipython-input-52-2eb4d7d064ec>, line 1)

In [53]:
mask = (names == 'Bob' | names == ‘Will’)

SyntaxError: invalid syntax (<ipython-input-53-890152968f46>, line 1)

In [54]:
mask = names == 'Bob' | names == 'Will'

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [55]:
mask = (names == 'Bob' | names == 'Will')

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [56]:
mask = (names == 'Bob') | (names == 'Will')

In [57]:
mask

array([ True, False,  True,  True,  True, False,  True], dtype=bool)

In [3]:
arr = np.empty((8,4))

In [4]:
for i in range(8):
    arr[i] = i

In [5]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [6]:
arr[[4,0,2,3]]

array([[ 4.,  4.,  4.,  4.],
       [ 0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [7]:
arr[[-1,-4,-2]]

array([[ 7.,  7.,  7.,  7.],
       [ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.]])

In [8]:
arr = np.arange(32).reshape((8,4))

In [9]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [20]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [66]:
arr[np.ix_[1, 5, 7, 2], [0, 3, 1, 2 ]]

TypeError: 'function' object has no attribute '__getitem__'

In [67]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2 ])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [68]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [69]:
np.dot(arr.T, arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [70]:
arr1 = np.arange(16).reshaape(2,2,4)

AttributeError: 'numpy.ndarray' object has no attribute 'reshaape'

In [71]:
arr1 = np.arange(16).reshaape((2,2,4))

AttributeError: 'numpy.ndarray' object has no attribute 'reshaape'

In [72]:
arr1 = np.arange(16).reshape((2,2,4))

In [73]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr1.transpose((0,1， 2))

SyntaxError: invalid syntax (<ipython-input-74-b9ddfa9a4927>, line 1)

In [76]:
arr1.transpose((0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr1.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [78]:
arr1.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [79]:
arr1.swapaxes(1,0)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [80]:
arr1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [81]:
arr1.transpose((1,2,0))

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [82]:
arr1.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [83]:
x = randn(8)

TypeError: 'module' object is not callable

In [84]:
import np.random.randn as randn

ImportError: No module named np.random.randn

In [85]:
x = np.random.randn(8)

In [86]:
y = np.random.randn(8)

In [87]:
x+y

array([ 1.27056143, -0.6556949 ,  1.48106364,  0.40351054,  0.60472763,
        1.75852598,  1.31418395, -0.45065827])

In [88]:
x substract y

SyntaxError: invalid syntax (<ipython-input-88-f57594fb3d0c>, line 1)

In [89]:
points = np.arange(-5, 5, 0.01)

In [90]:
xs, ys = np.meshgrid(points, points)

In [91]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [92]:
import matplotlib.pyplot as plt

In [93]:
z = np.sqrt(xs**2 + ys **2)

In [94]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [95]:
plt.imshow()

TypeError: imshow() takes at least 1 argument (0 given)

In [96]:
plt.imshow(z, cmap=plt.cm.gray);
plt.colorbar()

In [97]:
plt.title("Image")

In [99]:
plt.colorbar()

In [100]:
xarr = np.array([1,2,3,4,5])

In [101]:
yarr = np.array([1,2,3,4,5])

In [102]:
yarr = np.array([2,3,4,5,6])

In [103]:
cond = np.array([True, False, True, False, True])

In [104]:
rsult = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [105]:
rsult

[1, 3, 3, 5, 5]

In [106]:
result = np.where(cond,xarr,yarr)

In [107]:
result

array([1, 3, 3, 5, 5])

In [108]:
np.where(xarr<0, 2, -2)

array([-2, -2, -2, -2, -2])

In [109]:
xarr

array([1, 2, 3, 4, 5])

In [110]:
xarr.mean

<function mean>

In [111]:
xarr.mean()

3.0

In [112]:
arr = np.random.randn(5,4)

In [113]:
arr

array([[-0.23557178,  0.35583075,  0.50793383, -1.28703295],
       [ 0.71331081, -0.90485163,  0.3224369 , -0.81491802],
       [ 1.71511643, -0.51927902,  0.8881577 ,  1.22451529],
       [-1.48686703, -0.85738399,  1.56370638,  1.62073981],
       [ 0.22533397, -1.50003169, -1.22240611,  0.08332188]])

In [114]:
arr.mean(axis=1)

array([-0.16471004, -0.17100548,  0.8271276 ,  0.21004879, -0.60344549])

In [115]:
arr.mean(axis=0)

array([ 0.18626448, -0.68514311,  0.41196574,  0.1653252 ])

In [116]:
arr.cumsum

<function cumsum>

In [117]:
arr.cumprod()

array([-0.23557178, -0.08382368, -0.04257689,  0.05479785,  0.0390879 ,
       -0.03536875, -0.01140419,  0.00929348,  0.0159394 , -0.008277  ,
       -0.00735128, -0.00900175,  0.01338441, -0.01147558, -0.01794443,
       -0.02908326, -0.00655345,  0.00983038, -0.01201671, -0.00100126])

In [118]:
arr.cumsum(0)

array([[-0.23557178,  0.35583075,  0.50793383, -1.28703295],
       [ 0.47773903, -0.54902087,  0.83037073, -2.10195097],
       [ 2.19285546, -1.06829989,  1.71852843, -0.87743568],
       [ 0.70598843, -1.92568388,  3.28223481,  0.74330412],
       [ 0.9313224 , -3.42571557,  2.0598287 ,  0.82662601]])

In [119]:
arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

In [120]:
arr.sum(0)

array([12, 15, 18])

In [121]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr.cumsum(0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [123]:
(arr > 2).sum()

7

In [124]:
bools.all(arr)

NameError: name 'bools' is not defined

In [125]:
arr.all()

True

In [126]:
arr = np.random.rann(7)

AttributeError: 'module' object has no attribute 'rann'

In [127]:
arr = np.random.rand(7)

In [128]:
arr.all

<function all>

In [129]:
arr.all()

True

In [130]:
arr.sort()

In [131]:
arr

array([ 0.06226078,  0.08487142,  0.30585549,  0.52424626,  0.86104057,
        0.87436474,  0.95512007])

In [132]:
arr = np.random.randn(5,2)

In [133]:
arr.sort(0)

In [134]:
arr

array([[-0.72617028, -0.9867629 ],
       [-0.6579603 , -0.34057759],
       [-0.51516575, -0.22662455],
       [-0.12809007, -0.20548421],
       [ 0.88013125,  1.56847287]])

In [135]:
arr.sort(1)

In [136]:
arr

array([[-0.9867629 , -0.72617028],
       [-0.6579603 , -0.34057759],
       [-0.51516575, -0.22662455],
       [-0.20548421, -0.12809007],
       [ 0.88013125,  1.56847287]])

In [137]:
arr[int(len(arr)*0.25)]

array([-0.6579603 , -0.34057759])

In [138]:
arr.sort

<function sort>

In [139]:
arr.sort()

In [140]:
arr

array([[-0.9867629 , -0.72617028],
       [-0.6579603 , -0.34057759],
       [-0.51516575, -0.22662455],
       [-0.20548421, -0.12809007],
       [ 0.88013125,  1.56847287]])

In [141]:
arr = np.arange(10)

In [142]:
np.save('some_array', arr)

In [143]:
np.load('some_array.npy
    ')

SyntaxError: EOL while scanning string literal (<ipython-input-143-ebc0bef551f9>, line 1)

In [144]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
!cat array_ex.txt

'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [146]:
arr = np.loastxt('array_ex.txt', delimiter= ',')

AttributeError: 'module' object has no attribute 'loastxt'

In [147]:
np.ones(3)

array([ 1.,  1.,  1.])

In [148]:
from numpy.linalg import inv,qr

In [149]:
x = np.random.randn(5,5)

In [150]:
mat = x.T.dot(x)

In [151]:
mat

array([[ 2.3898544 ,  1.72232122, -0.20259784,  1.01744948,  0.57664296],
       [ 1.72232122,  1.81101469, -0.46950549,  0.95364711,  0.95799839],
       [-0.20259784, -0.46950549,  5.57350013, -1.7472335 ,  4.34082092],
       [ 1.01744948,  0.95364711, -1.7472335 ,  1.82623511, -0.73142294],
       [ 0.57664296,  0.95799839,  4.34082092, -0.73142294,  9.01899856]])

In [152]:
inv(mat)

array([[ 1.55651652, -1.49415335, -0.3081923 , -0.3087176 ,  0.18248663],
       [-1.49415335,  2.34205827,  0.3401233 , -0.19854693, -0.33304486],
       [-0.3081923 ,  0.3401233 ,  0.48289379,  0.36840096, -0.21896214],
       [-0.3087176 , -0.19854693,  0.36840096,  1.15868658, -0.04251527],
       [ 0.18248663, -0.33304486, -0.21896214, -0.04251527,  0.23652355]])

In [153]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   3.60822483e-16,   0.00000000e+00,
          1.59594560e-16,  -2.77555756e-17],
       [ -4.16333634e-16,   1.00000000e+00,  -8.32667268e-17,
          1.52655666e-16,  -2.77555756e-17],
       [  3.33066907e-16,  -2.22044605e-16,   1.00000000e+00,
         -1.66533454e-16,   0.00000000e+00],
       [ -1.38777878e-16,   1.66533454e-16,   8.32667268e-17,
          1.00000000e+00,   2.77555756e-17],
       [ -2.22044605e-16,   8.88178420e-16,   0.00000000e+00,
          4.99600361e-16,   1.00000000e+00]])

In [154]:
position = 0

In [155]:
walk = [position]

In [156]:
steps = 1000

In [157]:
for i in xrange(steps):
    step = 1 if random.randint(0, 1) else -1;
    position += step;
    walk.append(position)

NameError: name 'random' is not defined

In [158]:
for i in xrange(steps):
    step = 1 if np.random.randint(0, 1) else -1;
    position += step;
    walk.append(position)

In [159]:
plt.plot(steps, position, 'b--', linewidth = 1)

In [160]:
plt.figure(figsize=(8, 4))

In [161]:
plt.plot(steps, position, 'b--', linewidth = 1)

In [162]:
plt.matplotlib(steps, position, 'b--', linewidth = 1)

TypeError: 'module' object is not callable

In [163]:
plt.matplotlib(steps, position)

TypeError: 'module' object is not callable

In [164]:
nsteps = 1000

In [165]:
draws = np.random.randint(0, 2, nsteps)

In [166]:
steps = np.where(draws>0, 1, -1)

In [167]:
walk = steps.sum()

In [168]:
walk

20

In [169]:
walk = steps.cumsum()

In [170]:
walk.min()

-14

In [171]:
walk.max()

20

In [172]:
(np.abs(walk) == 10).argmax()

131

In [196]:
walk

array([ -1,   0,  -1,   0,   1,   0,  -1,  -2,  -1,   0,   1,   2,   3,
         2,   1,   0,   1,   0,   1,   0,   1,   0,   1,   2,   3,   2,
         3,   2,   3,   2,   3,   2,   1,   2,   1,   0,   1,   0,   1,
         0,  -1,  -2,  -1,  -2,  -3,  -4,  -3,  -4,  -3,  -2,  -3,  -2,
        -3,  -2,  -1,   0,  -1,   0,   1,   2,   1,   0,  -1,   0,   1,
         0,   1,   2,   3,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,
        -5,  -4,  -5,  -4,  -3,  -4,  -3,  -2,  -3,  -2,  -1,  -2,  -3,
        -2,  -3,  -2,  -3,  -2,  -3,  -4,  -5,  -4,  -3,  -4,  -5,  -6,
        -7,  -6,  -7,  -8,  -9,  -8,  -7,  -8,  -7,  -6,  -5,  -4,  -3,
        -4,  -5,  -4,  -5,  -6,  -5,  -6,  -7,  -6,  -7,  -6,  -7,  -8,
        -9, -10, -11, -12, -13, -14, -13, -12, -11, -10, -11, -10,  -9,
        -8,  -7,  -8,  -9,  -8,  -7,  -8,  -7,  -6,  -7,  -6,  -5,  -4,
        -5,  -6,  -7,  -6,  -7,  -8,  -7,  -6,  -7,  -6,  -7,  -6,  -7,
        -6,  -5,  -6,  -7,  -8,  -7,  -8,  -9, -10,  -9, -10, -1

In [174]:
hits = (np.abs(walk) >= 20).all(1)

ValueError: 'axis' entry is out of bounds

In [201]:
hits = (np.abs(walk) >= 10)

In [204]:
hits.any()

True

In [205]:
hits.sum()

203